[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Add mirrored to the collection
[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''for i = 1, 5 do\n\s+local card'''
position = "at"
payload = '''
	editions = {}
	for k, v in ipairs(G.P_CENTER_POOLS['Edition']) do
		table.insert(editions, {order=v.order, name=string.sub(v.key, 3, -1)})	
	end
	table.sort(editions, function (a, b) return a.order < b.order end )
	for k, v in ipairs(editions) do
		editions[k] = v.name	
	end
	for i = 1, #editions do
      local card
'''
match_indent = true