[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# overwrite :( can't think of a better way to do this
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')"
position = "at"
payload = '''
local card = ""
if G.GAME.pool_flags.badeline_break and not (G.GAME.used_jokers['j_ccc_badeline'] and not next(find_joker("Showman"))) and pseudorandom('baddie'..G.GAME.round_resets.ante) > 0.996 then
	card = create_card('Joker', area, nil, nil, nil, nil, 'j_ccc_badeline', 'bad')
else
	card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
end
'''
match_indent = true

# sustain glass cards
# patching smods for this
# the problem is that this does a bunch of things like sixth sense, but any other patches specifically to glass destroy will nuke mod compatibility... whatever, nobody will notice
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = "-- TARGET: card destroyed"
position = "after"
payload = '''
if next(SMODS.find_card('j_ccc_badeline')) then
	if SMODS.has_enhancement(card, 'm_glass') then
		destroyed = false
	end
end
'''
match_indent = true
