[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# injecting pointless machines into generate_uibox so i can copy misprint code without thinking too much (lmao...)
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "elseif self.ability.name == 'Banner' then loc_vars = {self.ability.extra}"
position = "after"
payload = '''
elseif self.ability.name == 'Pointless Machines' then
	local r_strings = {}
	local r_hearts_keymash = {"R<3EAST<3<H!", "ttt^a^reh.SS", "tera&*Ste&#raHH", "serT((H)).aa;"}
	local r_spades_keymash = {"Spac:::SE>>D", "!a@spes&&Dd", "deesS*DAPD((AP", "ES.ad##PSP#"}
	local r_diamonds_keymash = {"di##MDOsn", "osdDIA.N&M!!", "M*MaM,dins!^O", "NE%%id%OO^aMD"}
	local r_clubs_keymash = {"CUL&SL*BB", "sbluc!!((*@!)", "UC@bsLL]L", "PL!!)C**UBUBS"}
	local r_clear_keymash = {"<<.PLAY)", "&@!PLAY;;", "]PLAY/@&", "__PLAY.@>#"}
	local r_red_keymash = {"dsg x3c!!!O!]", "?d[{j, >.<fsA.Gg.<", "lAgsx,k##rf", "::R^E*AL**GL]", "es12_21sDLç", "++1UP1Up:"}
	local sequence_progress = 1
	r_strings[#r_strings+1] = pseudorandom_element(r_clear_keymash, pseudoseed('4starorderbytheway'))
	local last_used_element = r_strings[#r_strings]
	while sequence_progress < 6 do
		if pseudorandom(pseudoseed('randomthing'), 0, 1) > 0.5 then 
			r_strings[#r_strings+1] = pseudorandom_element(r_red_keymash, pseudoseed('redherring'))
		else
			if self.ability.extra.suits[sequence_progress] == 'Hearts' then
				r_strings[#r_strings+1] = pseudorandom_element(r_hearts_keymash, pseudoseed('hertas<3'))
				if r_strings[#r_strings] ~= last_used_element then
					sequence_progress = sequence_progress + 1
				end
			elseif self.ability.extra.suits[sequence_progress] == 'Spades' then
				r_strings[#r_strings+1] = pseudorandom_element(r_spades_keymash, pseudoseed('spdkagdeds'))
				if r_strings[#r_strings] ~= last_used_element then
					sequence_progress = sequence_progress + 1
				end
			elseif self.ability.extra.suits[sequence_progress] == 'Diamonds' then
				r_strings[#r_strings+1] = pseudorandom_element(r_diamonds_keymash, pseudoseed('dimaons'))
				if r_strings[#r_strings] ~= last_used_element then
					sequence_progress = sequence_progress + 1
				end
			elseif self.ability.extra.suits[sequence_progress] == 'Clubs' then
				r_strings[#r_strings+1] = pseudorandom_element(r_clubs_keymash, pseudoseed('lcusdbes'))
				if r_strings[#r_strings] ~= last_used_element then
					sequence_progress = sequence_progress + 1
				end
			end
		end
		if r_strings[#r_strings] == last_used_element then
			r_strings[#r_strings] = nil
		end
		last_used_element = r_strings[#r_strings]
	end
	main_start = {
		{n=G.UIT.O, config={object = DynaText({string = r_strings, colours = {lighten(G.C.BLACK, 0.4)},pop_in_rate = 9999999, silent = true, random_element = false, pop_delay = pseudorandom(pseudoseed('iamsodonewiththesepseudoseedsohmygod'), 0.95, 1.05), scale = 0.33, min_cycle_time = 0})}}
	}
'''
match_indent = true