[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# replace the placeholder if statement with (if G.deck.cards[#G.deck.cards]:get_id() ~= G.GAME.pool_flags.seeker_table.rank and G.deck.cards[#G.deck.cards].config.card.suit ~= G.GAME.pool_flags.seeker_table.suit then)
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK then"
position = "before"
payload = '''
if next(find_joker('Seeker')) then
	if G.deck.cards[#G.deck.cards]:get_id() == G.deck.cards[#G.deck.cards]:get_id() and G.deck.cards[#G.deck.cards].config.card.suit == G.deck.cards[#G.deck.cards].config.card.suit then
		local card = draw_card(G.deck,G.hand, i*100/hand_space,'up', true)
		delay(0.7)
		draw_card(G.hand,G.deck, i*100/hand_space, 'down', false, card)
		delay(0.1)
		G.deck:shuffle('see'..G.GAME.round_resets.ante)
		delay(0.1)
		draw_card(G.deck,G.hand, i*100/hand_space,'up', true)
		delay(0.7)
	else
		draw_card(G.deck,G.hand, i*100/hand_space,'up', true)
	end
else
'''
match_indent = true

# seeker fix pt. 2
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.discard_cards_from_highlighted = function(e, hook)"
position = "before"
payload = '''
end
'''
match_indent = true
