[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# unused patch file, delete later
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''end'''
position = "at"
payload = '''end'''
match_indent = true