[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# move Card:load()
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self:set_sprites(self.config.center, self.config.card)'
match_indent = true
position = 'after'
payload = '''
local obj = self.config.center
if obj.load and type(obj.load) == 'function' then
	obj:load(self, cardTable, other_card)
end
'''